robot_type: nix1_v2_joint21
asset:
  root: ./../../lumos_assets/
  xml: ${robot_type}/mjcf/${robot_type}.xml
  urdf: ${robot_type}/urdf/${robot_type}.urdf

dataset:
  folder: /../../motions/${robot_type}/pkl
  file: Mma_Kick_with_lastframe_repeat48_fps30.pkl
